python3 ./sources/01_generate_images.py
python3 ./sources/02_clustering_images.py
python3 ./sources/03_noise_gaussian.py
python3 ./sources/04_noise_gaussian_poisson.py
python3 ./sources/05_highlight_equalize.py
python3 ./sources/06_highlight_gamma.py
python3 ./sources/07_filtering.py
python3 ./sources/08_noise.py
python3 ./sources/08_a.py
python3 ./sources/08_b.py
python3 ./sources/08_c.py
python3 ./sources/09_colors.py
python3 ./sources/10_frequency.py
python3 ./sources/11_segmentation.py
python3 ./sources/12_morphology.py