python3 ./sources/01_generate_images.py
python3 ./sources/02_clustering_images.py
python3 ./sources/03_noise_gaussian.py
python3 ./sources/04_noise_gaussian_poisson.py
python3 ./sources/05_highlight_equalize.py
python3 ./sources/06_highlight_gamma.py
python3 ./sources/07_filtering.py
python3 ./sources/08_noise.py
python3 ./sources/08_a.py
python3 ./sources/08_b.py
python3 ./sources/08_c.py
python3 ./sources/09_colors.py
python3 ./sources/10_frequency.py
python3 ./sources/11_segmentation.py
python3 ./sources/12_morphology.py
python3 ./sources/13_texture_a.py
python3 ./sources/13_texture_b.py
python3 ./sources/13_texture_c.py
python3 ./sources/13_texture_e_3D_1.py
python3 ./sources/13_texture_e_barra_1.py
python3 ./sources/13_texture_d_1.py
python3 ./sources/13_texture_d_2.py
python3 ./sources/13_texture_d_3.py
python3 ./sources/13_texture_d_4.py
python3 ./sources/14_final_a.py
python3 ./sources/14_final_b.py
python3 ./sources/14_final_c.py
python3 ./sources/14_final_d.py
python3 ./sources/14_final_e.py
python3 ./sources/14_final_f.py
python3 ./sources/14_final_g.py
python3 ./sources/14_final_h.py
python3 ./sources/14_final_i.py
python3 ./sources/14_final_j.py
python3 ./sources/14_final_k.py
